List<Map<String, dynamic>> libraryData = [
  {
    'index': 1,
    'title': 'New Year\'s Day' ,
    'subject': 'Public Holiday	',
    'department': 'Architecture',
    'year': '03 January 2019	',
    'type': 'CD',
    'status': 'Out of Stock',
  },
  {
    'index': 2,
    'title': 'Memorial Day	',
    'subject': 'Graphics',
    'department': 'MBA',
    'year': 'Third Year',
    'type': 'DVD',
    'status': 'Out of Stock',
  },
  {
    'index': 3,
    'title': 'Christmas Day	',
    'subject': 'Politics',
    'department': 'Architecture',
    'year': 'Third Year',
    'type': 'Newspaper',
    'status': 'Out of Stock',
  },
  {
    'index': 4,
    'title': 'Annual Function	',
    'subject': 'Computer',
    'department': 'MBA',
    'year': 'Last Year',
    'type': 'Newspaper',
    'status': 'In Stock',
  },
  {
    'index': 5,
    'title': 'Web Programming',
    'subject': 'Mechanics',
    'department': 'Computer',
    'year': 'Third Year',
    'type': 'Book',
    'status': 'In Stock',
  },
  {
    'index': 6,
    'title': 'Designing',
    'subject': 'Designing',
    'department': 'Computer',
    'year': 'Third Year',
    'type': 'Newspaper',
    'status': 'Out of Stock',
  },
  {
    'index': 7,
    'title': 'Mechanics',
    'subject': 'Computer',
    'department': 'Computer Engineering',
    'year': 'Second Year',
    'type': 'DVD',
    'status': 'Out of Stock',
  },
  {
    'index': 8,
    'title': 'Computer Fundamental',
    'subject': 'Animation',
    'department': 'Mechanical',
    'year': 'Third Year',
    'type': 'CD',
    'status': 'In Stock',
  },
  {
    'index': 9,
    'title': 'Time History',
    'subject': 'Management',
    'department': 'Mechanical',
    'year': 'Third Year',
    'type': 'Newspaper',
    'status': 'Out of Stock',
  },
  {
    'index': 10,
    'title': 'Politics',
    'subject': 'Designing',
    'department': 'Mechanical',
    'year': 'Second Year',
    'type': 'Newspaper',
    'status': 'Out of Stock',
  },
  {
    'index': 11,
    'title': 'Designing',
    'subject': 'Mechanics',
    'department': 'Computer',
    'year': 'Third Year',
    'type': 'Newspaper',
    'status': 'Out of Stock',
  },
  {
    'index': 12,
    'title': 'Mechanics',
    'subject': 'Computer',
    'department': 'Computer Engineering',
    'year': 'Second Year',
    'type': 'DVD',
    'status': 'Out of Stock',
  },
  {
    'index': 13,
    'title': 'Computer Fundamental',
    'subject': 'Animation',
    'department': 'Mechanical',
    'year': 'Third Year',
    'type': 'CD',
    'status': 'In Stock',
  },
  {
    'index': 14,
    'title': 'Time History',
    'subject': 'Management',
    'department': 'Mechanical',
    'year': 'Third Year',
    'type': 'Newspaper',
    'status': 'Out of Stock',
  },
  {
    'index': 15,
    'title': 'Politics',
    'subject': 'Designing',
    'department': 'Mechanical',
    'year': 'Second Year',
    'type': 'Newspaper',
    'status': 'Out of Stock',
  },
];
